# Created with YamlCreate.ps1 v2.2.2 $debug=QUSU.CRLF.7-2-9.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: trinsic.cli
PackageVersion: 1.9.0
PackageLocale: en-US
Publisher: Trinsic
PublisherUrl: https://github.com/trinsic-id
PublisherSupportUrl: https://github.com/trinsic-id/sdk/issues
# PrivacyUrl:
Author: Trinsic
PackageName: trinsic
PackageUrl: https://github.com/trinsic-id/sdk
License: Apache-2.0
LicenseUrl: https://github.com/trinsic-id/sdk/blob/main/LICENSE
Copyright: Copyright (c) Trinsic
# CopyrightUrl:
ShortDescription: Trinsic Ecosystems Command Line Interface
# Description:
Moniker: trinsic-cli
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
