# Created with YamlCreate.ps1 v2.2.2 $debug=QUSU.CRLF.7-2-9.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: trinsic.cli
PackageVersion: 1.9.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
